### ISSUE TITLE
scylla monitor stuck at wait for Loki container

### ISSUE THREAD

**Issue by asias** [scylladb/scylla-monitoring#1143]
```
commit 644759576913fc8b86c45433936e0c19df2ecb75 (HEAD -> l7.2020.11.17, origin/master, origin/HEAD)
Merge: c20eaa9 c0a4327
Author: Amnon Heiman <amnon@cloudius-systems.com>
Date:   Mon Nov 16 16:27:34 2020 +0200

    Merge pull request #1142 from amnonh/loki
    
    Adding Loki as an alert source to the monitoring stack
```

```
$ cat scylla_servers.hj.yml 
# List Scylla end points

# An example with a single cluster and two DC
- targets:
       - 172.17.0.110:9180
  labels:
       cluster: c1
       dc: mydc1
- targets:
       - 172.17.0.120:9180
  labels:
       cluster: c1
       dc: mydc2
- targets:
       - 172.17.0.130:9180
  labels:
       cluster: c1
       dc: mydc3


$ ./start-all.sh -l -v master -s scylla_servers.hj.yml
*****************************************************
* WARNING: You are using the unstable master branch *
* Check the README.md file for the stable releases  *
*****************************************************

Wait for alert manager container to start
Wait for Loki container to start.
```

**Comment by asias** [comment]
After `git revert 644759576913fc8b86c45433936e0c19df2ecb75 -m 1`:

```
$ ./start-all.sh -l -v master -s scylla_servers.hj.yml
Error: no container with name or ID aprom found: no such container
e48b1972a966b65ebfcbd62232ebe9dd04b37033fdda43fbcbf10f21b9d08957
e48b1972a966b65ebfcbd62232ebe9dd04b37033fdda43fbcbf10f21b9d08957

*****************************************************
* WARNING: You are using the unstable master branch *
* Check the README.md file for the stable releases  *
*****************************************************

Wait for alert manager container to start
Wait for Prometheus container to start........
Error: Prometheus container failed to start
For more information use: docker logs aprom
[asias@hjpc2 scylla-grafana-monitoring]$ docker logs aprom
level=info ts=2020-11-17T11:33:07.238Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-11-17T11:33:07.238Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.1, branch=HEAD, revision=ecee9c8abfd118f139014cb1b174b08db3f342cf)"
level=info ts=2020-11-17T11:33:07.238Z caller=main.go:338 build_context="(go=go1.14.2, user=root@2117a9e64a7e, date=20200507-16:51:47)"
level=info ts=2020-11-17T11:33:07.238Z caller=main.go:339 host_details="(Linux 5.8.17-100.fc31.x86_64 #1 SMP Thu Oct 29 18:58:48 UTC 2020 x86_64 hjpc2 (none))"
level=info ts=2020-11-17T11:33:07.238Z caller=main.go:340 fd_limits="(soft=20000, hard=20000)"
level=info ts=2020-11-17T11:33:07.238Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-11-17T11:33:07.239Z caller=query_logger.go:109 component=activeQueryTracker msg="Failed to create directory for logging active queries"
level=error ts=2020-11-17T11:33:07.239Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=data/queries.active err="open data/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x26b4395, 0x5, 0x14, 0x2e940a0, 0xc0003c8540, 
        /app/promql/query_logger.go:117 +0x4cd
main.main()
        /app/cmd/prometheus/main.go:368 +0x4ed8
```

**Comment by asias** [comment]
It is the same with scylla-monitoring-3.5.1
```
$ ./start-all.sh -l -v master -s scylla_servers.hj.yml
Error: can only create exec sessions on running containers: container state improper
58e6ff04ecbff42d20af2f2fd3c5c65cc211b39d2efee12600d1e753444ea877
43d360ff745ee0bb552cfc6ac5f32bc7f981000b0fd8e56a803718423a4e0320
43d360ff745ee0bb552cfc6ac5f32bc7f981000b0fd8e56a803718423a4e0320
Wait for alert manager container to start
Wait for Prometheus container to start........
Error: Prometheus container failed to start
For more information use: docker logs aprom
[asias@hjpc2 scylla-grafana-monitoring]$ docker logs aprom
level=info ts=2020-11-17T11:35:41.400Z caller=main.go:294 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-11-17T11:35:41.400Z caller=main.go:330 msg="Starting Prometheus" version="(version=2.15.2, branch=HEAD, revision=d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)"
level=info ts=2020-11-17T11:35:41.400Z caller=main.go:331 build_context="(go=go1.13.5, user=root@688433cf4ff7, date=20200106-14:50:51)"
level=info ts=2020-11-17T11:35:41.400Z caller=main.go:332 host_details="(Linux 5.8.17-100.fc31.x86_64 #1 SMP Thu Oct 29 18:58:48 UTC 2020 x86_64 hjpc2 (none))"
level=info ts=2020-11-17T11:35:41.400Z caller=main.go:333 fd_limits="(soft=20000, hard=20000)"
level=info ts=2020-11-17T11:35:41.400Z caller=main.go:334 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-11-17T11:35:41.401Z caller=query_logger.go:107 component=activeQueryTracker msg="Failed to create directory for logging active queries"
level=error ts=2020-11-17T11:35:41.401Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=data/queries.active err="open data/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x24deddb, 0x5, 0x14, 0x2c635a0, 0xc0007b7590, 0x2c635a0)
        /app/promql/query_logger.go:115 +0x48c
main.main()
        /app/cmd/prometheus/main.go:362 +0x5229

```

**Comment by amnonh** [comment]
Loki is only relevant to master.
This seems like a directory permission problem.

Can you check your user id? there was an issue with GCE that gives user id in a range above what docker expect.
If that is the case, you can use `sudo` as a workaround
@asias one more thing, are you using podman or docker? and what version

**Comment by asias** [comment]
> Loki is only relevant to master.

Yes. I tried older release version. They failed with other issues.

> This seems like a directory permission problem.
> 
> Can you check your user id? there was an issue with GCE that gives user id in a range above what docker expect.
> If that is the case, you can use `sudo` as a workaround
> @asias one more thing, are you using podman or docker? and what version

$ podman -v
podman version 1.9.3

$ id
uid=1000(asias) gid=1000(asias) groups=1000(asias),10(wheel),18(dialout),964(vboxusers),970(wireshark)

BTW, do we have any automatic QA for master or release version?

**Comment by asias** [comment]
> Loki is only relevant to master.
> This seems like a directory permission problem.
> 
> Can you check your user id? there was an issue with GCE that gives user id in a range above what docker expect.
> If that is the case, you can use `sudo` as a workaround

sudo did not work with 3.5.1 release too.

```
$ git reset --hard scylla-monitoring-3.5.1
$ sudo ./start-all.sh -l -v master -s scylla_servers.hj.yml
Error: no container with name or ID aprom found: no such container
Running as root is not advised, please check the documentation on how to run as non-root user
Wait for alert manager container to start
Error: Alertmanager container failed to start
```

**Comment by amnonh** [comment]
I'm pretty sure this is a file's permissions problem, maybe it's related to podman, I'll try to reproduce it on an image, what fedora version are you using?

**Comment by asias** [comment]
$ cat /etc/redhat-release 
Fedora release 31 (Thirty One)

**Comment by asias** [comment]
FYI: on top of commit 09f04c5e2bc8704cd0a439af7fbc2e1139ab0e99
+
```
diff --git a/start-all.sh b/start-all.sh
index bc93b38..37cacbd 100755
--- a/start-all.sh
+++ b/start-all.sh
@@ -209,7 +209,10 @@ else
     DATA_DIR="-v "$(readlink -m $DATA_DIR)":/prometheus/data:Z"
 fi
 
-docker run -d $DOCKER_PARAM $USER_PERMISSIONS \
+echo $USER_PERMISSIONS
+echo $DATA_DIR
+#docker run -d $DOCKER_PARAM $USER_PERMISSIONS \
+docker run -d $DOCKER_PARAM \
      $DATA_DIR \
      -v $PWD/prometheus/build/prometheus.yml:/etc/prometheus/prometheus.yml:Z \
      -v $PROMETHEUS_RULES:/etc/prometheus/prometheus.rules.yml:Z \
@@ -263,4 +266,4 @@ for val in "${GRAFANA_DASHBOARD_ARRAY[@]}"; do
         GRAFANA_DASHBOARD_COMMAND="$GRAFANA_DASHBOARD_COMMAND -j $val"
 done
 
-./start-grafana.sh $BIND_ADDRESS_CONFIG -p $DB_ADDRESS -D "$DOCKER_PARAM" $GRAFANA_PORT $EXTERNAL_VOLUME -m $AM_ADDRESS -M $MANAGER_VERSION -v $VERSIONS $GRAFANA_ENV_COMMAND $GRAFANA_DASHBOARD_COMMAND $GRAFANA_ADMIN_PASSWORD
+./start-grafana.sh -l $BIND_ADDRESS_CONFIG -p $DB_ADDRESS -D "$DOCKER_PARAM" $GRAFANA_PORT $EXTERNAL_VOLUME -m $AM_ADDRESS -M $MANAGER_VERSION -v $VERSIONS $GRAFANA_ENV_COMMAND $GRAFANA_DASHBOARD_COMMAND $GRAFANA_ADMIN_PASSWORD
```

works for me.


I tried the patch above + 3.5.1. It did not work for me.

**Comment by amnonh** [comment]
There is actually two issues here, one is that star-loki.sh does not start on podman, this is a result of `selinux` getting in the way, 
```
$ getenforce
Enforcing
$ sudo setenforce 0
$ getenforce
Permissive
```

The second issue is #1145 which I'll send a patch soon

You can also disable loki with:
`--no-loki` flag to strat-all.sh

**Comment by asias** [comment]
Let me know when you have the fix. I can test it here.

**Comment by asias** [comment]
> There is actually two issues here, one is that star-loki.sh does not start on podman, this is a result of `selinux` getting in the way,
> 
> ```
> $ getenforce
> Enforcing
> $ sudo setenforce 0
> $ getenforce
> Permissive
> ```

selinux is not a problem for me becuase:

$ getenforce
Disabled

**Comment by amnonh** [comment]
> Let me know when you have the fix. I can test it here.

It's already in master

**Comment by amnonh** [comment]
> > There is actually two issues here, one is that star-loki.sh does not start on podman, this is a result of `selinux` getting in the way,
> > ```
> > $ getenforce
> > Enforcing
> > $ sudo setenforce 0
> > $ getenforce
> > Permissive
> > ```
> 
> selinux is not a problem for me becuase:
> 
> $ getenforce
> Disabled

Can you update your podman and see if the problem persists?

**Comment by asias** [comment]
> > > There is actually two issues here, one is that star-loki.sh does not start on podman, this is a result of `selinux` getting in the way,
> > > ```
> > > $ getenforce
> > > Enforcing
> > > $ sudo setenforce 0
> > > $ getenforce
> > > Permissive
> > > ```
> > 
> > 
> > selinux is not a problem for me becuase:
> > $ getenforce
> > Disabled
> 
> Can you update your podman and see if the problem persists?

After upgrade podman, it works.

**Comment by asias** [comment]
Loki sitll does not work. I meant the permission issue is gone.

**Comment by asias** [comment]
I tried again without disabling loki after upgrade podman. Cool, It indeed works now.
