### ISSUE TITLE
Failed getting screenshot with grafanarender plugin

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla-monitoring#1274]
*Installation details*
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) overview-master
Scylla-Version: 4.5.dev

Screenshot is next created after with grafanarender plugin. if open any dashboard:
http://13.51.64.68:3000/d/overview-master/overview?orgId=1&refresh=30s

and request the render to create screenshot:
http://13.51.64.68:3000/render/d/overview-master/overview?orgId=1&refresh=30s&width=1920&height=5000

Next error were got:
![Screenshot from 2021-02-09 13-05-40](https://user-images.githubusercontent.com/44991177/107323246-7eeeee00-6ad8-11eb-8632-7e40b224de67.png)

Next erorrs in grafanarender docker log:
```
{"url":"/render?deviceScaleFactor=1.000000&domain=&encoding=&height=2500&renderKey=7GLrI01s40p1wisoa6qSn3gQGHBBf6D7&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%3ForgId%3D1%26from%3D1612848955237%26to%3D1612850755237%26width%3D1000%26height%3D2500%26render%3D1&width=1000","stack":"Error: Protocol error (Network.deleteCookies): An http or https url URL must be specified\n    at /usr/src/app/node_modules/puppeteer/lib/Connection.js:183:56\n    at new Promise (<anonymous>)\n    at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:182:12)\n    at Page.deleteCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:396:26)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n  -- ASYNC --\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
{"message":"::ffff:127.0.0.1 - - [09/Feb/2021:06:07:04 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=&encoding=&height=2500&renderKey=7GLrI01s40p1wisoa6qSn3gQGHBBf6D7&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%3ForgId%3D1%26from%3D1612848955237%26to%3D1612850755237%26width%3D1000%26height%3D2500%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Grafana/7.3.5\"\n","level":"error"}
{"url":"/render?deviceScaleFactor=1.000000&domain=&encoding=&height=2500&renderKey=jtMUFZ2sjkWB2e756taol1e6uE9wYrLl&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%3ForgId%3D1%26from%3D1612848955237%26to%3D1612850755237%26width%3D1000%26height%3D2500%26render%3D1&width=1000","stack":"Error: Protocol error (Network.deleteCookies): An http or https url URL must be specified\n    at /usr/src/app/node_modules/puppeteer/lib/Connection.js:183:56\n    at new Promise (<anonymous>)\n    at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:182:12)\n    at Page.deleteCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:396:26)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n  -- ASYNC --\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
{"message":"::ffff:127.0.0.1 - - [09/Feb/2021:06:07:05 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=&encoding=&height=2500&renderKey=jtMUFZ2sjkWB2e756taol1e6uE9wYrLl&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%3ForgId%3D1%26from%3D1612848955237%26to%3D1612850755237%26width%3D1000%26height%3D2500%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Grafana/7.3.5\"\n","level":"error"}
{"url":"/render?deviceScaleFactor=1.000000&domain=&encoding=&height=2500&renderKey=m1VSH5sOkbpbvrK3uAXX19Npnuh4ACwQ&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%3ForgId%3D1%26from%3D1612848955237%26to%3D1612850755237%26width%3D1000%26height%3D2500%26render%3D1&width=1000","stack":"Error: Protocol error (Network.deleteCookies): An http or https url URL must be specified\n    at /usr/src/app/node_modules/puppeteer/lib/Connection.js:183:56\n    at new Promise (<anonymous>)\n    at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:182:12)\n    at Page.deleteCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:396:26)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n  -- ASYNC --\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
{"message":"::ffff:127.0.0.1 - - [09/Feb/2021:06:07:06 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=&encoding=&height=2500&renderKey=m1VSH5sOkbpbvrK3uAXX19Npnuh4ACwQ&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%3ForgId%3D1%26from%3D1612848955237%26to%3D1612850755237%26width%3D1000%26height%3D2500%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Grafana/7.3.5\"\n","level":"error"}
{"url":"/render?deviceScaleFactor=1.000000&domain=&encoding=&height=5000&renderKey=pBwkGOyXD3MyAaNkFarA4xWQBUhHQHzg&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%2Foverview%3ForgId%3D1%26refresh%3D30s%26width%3D1920%26height%3D5000%26render%3D1&width=1920","stack":"Error: Protocol error (Network.deleteCookies): An http or https url URL must be specified\n    at /usr/src/app/node_modules/puppeteer/lib/Connection.js:183:56\n    at new Promise (<anonymous>)\n    at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:182:12)\n    at Page.deleteCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:396:26)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n  -- ASYNC --\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.setCookie (/usr/src/app/node_modules/puppeteer/lib/Page.js:414:16)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
{"message":"::ffff:127.0.0.1 - - [09/Feb/2021:06:13:20 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=&encoding=&height=5000&renderKey=pBwkGOyXD3MyAaNkFarA4xWQBUhHQHzg&timeout=60&timezone=&url=http%3A%2F%2F%3A3000%2Fd%2Foverview-master%2Foverview%3ForgId%3D1%26refresh%3D30s%26width%3D1920%26height%3D5000%26render%3D1&width=1920 HTTP/1.1\" 500 96 \"-\" \"Grafana/7.3.5\"\n","level":"error"}
```

**Comment by amnonh** [comment]
can you please update scylla-monitoring version?

**Comment by aleksbykov** [comment]
the latest is 3.6?

**Comment by amnonh** [comment]
release 3.6.1 was released yesterday, so it could be 3.6, 3.6.1 or master, it should be at the botttom left of each dashboard

**Comment by aleksbykov** [comment]
it is master http://13.51.64.68:3000/

**Comment by amnonh** [comment]
Closing
