### ISSUE TITLE
prometheus docker crashed

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-monitoring#655]
```
[jenkins@aws-eu-builder4 latest]$ grep start-all.sh job.log
2019-06-26 10:12:06,950 remote           L0203 DEBUG| [10.0.26.65] [stdout]  extracting: scylla-grafana-monitoring-branch-2.3/enterprise-start-all.sh  
2019-06-26 10:12:07,027 remote           L0203 DEBUG| [10.0.26.65] [stdout]   inflating: scylla-grafana-monitoring-branch-2.3/start-all.sh  
./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -l -v master -b "-web.enable-admin-api"
./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -l -v master -b \"-web.enable-admin-api\"
./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -l -v master -b "-web.enable-admin-api"
./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -l -v master -b \"-web.enable-admin-api\"
./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -l -v master -b "-web.enable-admin-api"
./start-all.sh -s /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/scylla_servers.yml -n /var/lib/scylla/scylla-grafana-monitoring-branch-2.3/config/node_exporter_servers.yml -d /var/lib/scylla/scylla-grafana-monitoring-data -l -v master -b \"-web.enable-admin-api\"
```

```
[jenkins@aws-eu-builder4 latest]$ /bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpMASaFY -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /home/jenkins/.ssh/scylla-qa-ec2 10.0.26.65
Last login: Thu Jun 27 09:18:48 2019 from ip-10-0-219-218.eu-west-1.compute.internal
[centos@ip-10-0-26-65 ~]$ sudo docker container ls
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
f81a7279b089        grafana/grafana:5.4.2       "/run.sh"                4 hours ago         Up 4 hours                              agraf
b12f226fa6e7        prom/alertmanager:v0.16.0   "/bin/alertmanager..."   4 hours ago         Up 4 hours                              aalert
```
```
[centos@ip-10-0-26-65 ~]$ sudo docker logs aprom
level=info ts=2019-06-27T04:36:46.294475489Z caller=main.go:302 msg="Starting Prometheus" version="(version=2.7.2, branch=HEAD, revision=82f98c825a1437c0a24056eb4dc986d9a3fc7fae)"
level=info ts=2019-06-27T04:36:46.294567929Z caller=main.go:303 build_context="(go=go1.11.5, user=root@ab86c672c33a, date=20190302-14:57:04)"
level=info ts=2019-06-27T04:36:46.294601754Z caller=main.go:304 host_details="(Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 ip-10-0-26-65.eu-west-1.compute.internal (none))"
level=info ts=2019-06-27T04:36:46.29463218Z caller=main.go:305 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-06-27T04:36:46.29467106Z caller=main.go:306 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-06-27T04:36:46.298818906Z caller=main.go:620 msg="Starting TSDB ..."
level=info ts=2019-06-27T04:36:46.298887484Z caller=web.go:416 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-06-27T04:36:46.300137906Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1561543952169 maxt=1561550400000 ulid=01DE9YN4XJW2GVKECRMD038CW0
level=info ts=2019-06-27T04:36:46.300300492Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1561550400000 maxt=1561572000000 ulid=01DEASDD2R7SZY1GHG77R9AP34
level=info ts=2019-06-27T04:36:46.300363017Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1561593600000 maxt=1561600800000 ulid=01DEBE09JHYQDC6RWY6VAR6RKE
level=info ts=2019-06-27T04:36:46.300431911Z caller=repair.go:48 component=tsdb msg="found healthy block" mint=1561572000000 maxt=1561593600000 ulid=01DEBE0JS3TB7TM93TY1W564XZ
level=warn ts=2019-06-27T04:37:09.806507504Z caller=head.go:440 component=tsdb msg="unknown series references" count=7869
level=info ts=2019-06-27T04:37:09.860251827Z caller=main.go:635 msg="TSDB started"
level=info ts=2019-06-27T04:37:09.861377204Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-06-27T04:37:09.88859733Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-06-27T04:37:09.889020884Z caller=main.go:589 msg="Server is ready to receive web requests."
level=info ts=2019-06-27T05:00:03.435000305Z caller=compact.go:443 component=tsdb msg="write block" mint=1561600800000 maxt=1561608000000 ulid=01DEBMW0TSSDZ1EFDAXWREE27B
level=info ts=2019-06-27T05:00:04.273758691Z caller=head.go:526 component=tsdb msg="head GC completed" duration=83.399067ms
level=info ts=2019-06-27T05:00:10.095051569Z caller=head.go:573 component=tsdb msg="WAL checkpoint complete" first=34 last=38 duration=5.820325732s
level=info ts=2019-06-27T07:00:02.879127784Z caller=compact.go:443 component=tsdb msg="write block" mint=1561608000000 maxt=1561615200000 ulid=01DEBVQR2F9XJHSE2KSY55TWT2
level=info ts=2019-06-27T07:00:03.333387183Z caller=head.go:526 component=tsdb msg="head GC completed" duration=51.118368ms
level=info ts=2019-06-27T07:00:11.79508516Z caller=head.go:573 component=tsdb msg="WAL checkpoint complete" first=39 last=43 duration=8.461624548s
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1d3a8ca, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc048000000, 0x4000000, 0x3053038)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x30397a0, 0x4000000, 0x3039878, 0x7f26e52312f8)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x30397a0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x30397a0, 0x1, 0x3053048, 0x400)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x30397a0, 0x1, 0xe, 0x7f26e55fffff)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x30397a0, 0x1, 0x7f26e501000e, 0x7f26e5231390)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.(*mcentral).grow(0x303ae58, 0x0)
	/usr/local/go/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0x303ae58, 0x1ff)
	/usr/local/go/src/runtime/mcentral.go:106 +0x2f8
runtime.(*mcache).refill(0x7f272ddeb6c0, 0xc00004450e)
	/usr/local/go/src/runtime/mcache.go:122 +0x95
runtime.(*mcache).nextFree.func1()
	/usr/local/go/src/runtime/malloc.go:749 +0x32
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229
goroutine 33544 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc02ab9eb18 sp=0xc02ab9eb10 pc=0x459f90
runtime.(*mcache).nextFree(0x7f272ddeb6c0, 0xe, 0xc000058380, 0x7f26e6f4f54a, 0x7f272ddeb6c0)
	/usr/local/go/src/runtime/malloc.go:748 +0xb6 fp=0xc02ab9eb70 sp=0xc02ab9eb18 pc=0x40b6e6
runtime.mallocgc(0x60, 0x1bef7c0, 0xf5ea01, 0x7f270fd3deb2)
	/usr/local/go/src/runtime/malloc.go:903 +0x793 fp=0xc02ab9ec10 sp=0xc02ab9eb70 pc=0x40c033
runtime.newobject(0x1bef7c0, 0x1fc6800)
	/usr/local/go/src/runtime/malloc.go:1032 +0x38 fp=0xc02ab9ec40 sp=0xc02ab9ec10 pc=0x40c418
github.com/prometheus/tsdb.newChunkSeriesIterator(0xc03b1cf0e0, 0xc, 0xc, 0x0, 0x0, 0x0, 0x16b92fd6b10, 0x16b98261100, 0x15cd254)
	/app/vendor/github.com/prometheus/tsdb/querier.go:769 +0x78 fp=0xc02ab9ec78 sp=0xc02ab9ec40 pc=0x15cce78
github.com/prometheus/tsdb.(*chunkSeries).Iterator(0xc003acaba0, 0xc02cb9b3e0, 0xc02ab9ed40)
	/app/vendor/github.com/prometheus/tsdb/querier.go:654 +0x6e fp=0xc02ab9ecd0 sp=0xc02ab9ec78 pc=0x15cc88e
github.com/prometheus/tsdb.newChainedSeriesIterator(0xc03035d3e0, 0x2, 0x2, 0x1)
	/app/vendor/github.com/prometheus/tsdb/querier.go:698 +0x45 fp=0xc02ab9ed08 sp=0xc02ab9ecd0 pc=0x15cc9f5
github.com/prometheus/tsdb.(*chainedSeries).Iterator(0xc03035d3c0, 0x0, 0x408684b5e91f7802)
	/app/vendor/github.com/prometheus/tsdb/querier.go:682 +0x40 fp=0xc02ab9ed38 sp=0xc02ab9ed08 pc=0x15cc980
github.com/prometheus/tsdb.(*chainedSeriesIterator).Seek(0xc04734d320, 0x16b96aa9490, 0xc023ad5ea0)
	/app/vendor/github.com/prometheus/tsdb/querier.go:706 +0x91 fp=0xc02ab9ed88 sp=0xc02ab9ed38 pc=0x15ccb41
github.com/prometheus/prometheus/storage.(*BufferedSeriesIterator).Seek(0xc02cb9b410, 0x16b96ab09c0, 0x10)
	/app/storage/buffer.go:86 +0xd0 fp=0xc02ab9edb0 sp=0xc02ab9ed88 pc=0x157ba20
github.com/prometheus/prometheus/promql.(*evaluator).matrixIterSlice(0xc0000c2230, 0xc02cb9b410, 0x16b96aa9490, 0x16b96ab09c0, 0xc0067da200, 0x0, 0x10, 0xc02cb9b3e0, 0x1, 0x1)
	/app/promql/engine.go:1310 +0x110 fp=0xc02ab9ee40 sp=0xc02ab9edb0 pc=0x15f1320
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc0000c2230, 0x1fc6140, 0xc008b6e620, 0xc00df0e1b0, 0x2)
	/app/promql/engine.go:1010 +0x75a fp=0xc02ab9f430 sp=0xc02ab9ee40 pc=0x15ed8aa
github.com/prometheus/prometheus/promql.(*evaluator).rangeEval(0xc0000c2230, 0xc032a8ace0, 0xc02aba0048, 0x2, 0x2, 0x0, 0x1, 0x1)
	/app/promql/engine.go:772 +0x158e fp=0xc02ab9fae8 sp=0xc02ab9f430 pc=0x15ecb9e
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc0000c2230, 0x1fc60c0, 0xc0032a41e0, 0x1, 0xc00df0e120)
	/app/promql/engine.go:910 +0x30ef fp=0xc02aba00d8 sp=0xc02ab9fae8 pc=0x15f023f
github.com/prometheus/prometheus/promql.(*evaluator).rangeEval(0xc0000c2230, 0xc03034ff10, 0xc008b6e660, 0x2, 0x2, 0x0, 0x1b7d760, 0xc02e90bf50)
	/app/promql/engine.go:772 +0x158e fp=0xc02aba0790 sp=0xc02aba00d8 pc=0x15ecb9e
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc0000c2230, 0x1fc6140, 0xc008b6e680, 0xc02aba0de0, 0xc0000c2230)
	/app/promql/engine.go:951 +0x1264 fp=0xc02aba0d80 sp=0xc02aba0790 pc=0x15ee3b4
github.com/prometheus/prometheus/promql.(*evaluator).Eval(0xc0000c2230, 0x1fc6140, 0xc008b6e680, 0x0, 0x0, 0x0, 0x0)
	/app/promql/engine.go:699 +0x80 fp=0xc02aba0db8 sp=0xc02aba0d80 pc=0x15eb2a0
github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc0004d1470, 0x1fd4ac0, 0xc02523c7b0, 0xc0096a01e0, 0xc0032a4230, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/app/promql/engine.go:478 +0xdad fp=0xc02aba1098 sp=0xc02aba0db8 pc=0x15e9c1d
github.com/prometheus/prometheus/promql.(*Engine).exec(0xc0004d1470, 0x1fd4ac0, 0xc02523c7b0, 0xc0096a01e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/app/promql/engine.go:390 +0x59f fp=0xc02aba1158 sp=0xc02aba1098 pc=0x15e8bef
github.com/prometheus/prometheus/promql.(*query).Exec(0xc0096a01e0, 0x1fd4a00, 0xc00f691080, 0xc0004d65a0)
	/app/promql/engine.go:178 +0x94 fp=0xc02aba1220 sp=0xc02aba1158 pc=0x15e7024
github.com/prometheus/prometheus/web/api/v1.(*API).queryRange(0xc000456140, 0xc00a21b400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/web/api/v1/api.go:358 +0xa55 fp=0xc02aba1580 sp=0xc02aba1220 pc=0x178cb55
github.com/prometheus/prometheus/web/api/v1.(*API).queryRange-fm(0xc00a21b400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/app/web/api/v1/api.go:226 +0x70 fp=0xc02aba1610 sp=0xc02aba1580 pc=0x1799040
github.com/prometheus/prometheus/web/api/v1.(*API).Register.func1.1(0x1fc6440, 0xc008b6e460, 0xc00a21b400)
	/app/web/api/v1/api.go:205 +0x8e fp=0xc02aba16a8 sp=0xc02aba1610 pc=0x179840e
net/http.HandlerFunc.ServeHTTP(0xc00029eea0, 0x1fc6440, 0xc008b6e460, 0xc00a21b400)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc02aba16d0 sp=0xc02aba16a8 pc=0x6b0f84
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP(0x1fb6c60, 0xc00029eea0, 0x7f26f58724a0, 0xc0032a4050, 0xc00a21b400)
	/app/util/httputil/compression.go:90 +0x7c fp=0xc02aba1708 sp=0xc02aba16d0 pc=0x178a04c
github.com/prometheus/prometheus/util/httputil.CompressionHandler.ServeHTTP-fm(0x7f26f58724a0, 0xc0032a4050, 0xc00a21b400)
	/app/web/web.go:295 +0x57 fp=0xc02aba1740 sp=0xc02aba1708 pc=0x1798e27
github.com/prometheus/prometheus/web.(*Handler).testReady.func1(0x7f26f58724a0, 0xc0032a4050, 0xc00a21b400)
	/app/web/web.go:391 +0x55 fp=0xc02aba17a0 sp=0xc02aba1740 pc=0x17c5a95
net/http.HandlerFunc.ServeHTTP(0xc00029efa0, 0x7f26f58724a0, 0xc0032a4050, 0xc00a21b400)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc02aba17c8 sp=0xc02aba17a0 pc=0x6b0f84
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x1fc5900, 0xc008b6e420, 0xc00a21b400)
	/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:196 +0xe9 fp=0xc02aba1848 sp=0xc02aba17c8 pc=0x1774819
net/http.HandlerFunc.ServeHTTP(0xc000844480, 0x1fc5900, 0xc008b6e420, 0xc00a21b400)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc02aba1870 sp=0xc02aba1848 pc=0x6b0f84
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x1fc5900, 0xc008b6e420, 0xc00a21b400)
	/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:76 +0xb5 fp=0xc02aba18f8 sp=0xc02aba1870 pc=0x17743c5
github.com/prometheus/common/route.(*Router).handle.func1(0x1fc5900, 0xc008b6e420, 0xc00a21b300, 0x0, 0x0, 0x0)
	/app/vendor/github.com/prometheus/common/route/route.go:60 +0x2b6 fp=0xc02aba19d0 sp=0xc02aba18f8 pc=0x17887f6
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0000b1d40, 0x1fc5900, 0xc008b6e420, 0xc00a21b300)
	/app/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6cf fp=0xc02aba1ab0 sp=0xc02aba19d0 pc=0x17847df
github.com/prometheus/common/route.(*Router).ServeHTTP(0xc00029e880, 0x1fc5900, 0xc008b6e420, 0xc00a21b300)
	/app/vendor/github.com/prometheus/common/route/route.go:98 +0x4c fp=0xc02aba1ae0 sp=0xc02aba1ab0 pc=0x178840c
net/http.StripPrefix.func1(0x1fc5900, 0xc008b6e420, 0xc00a21b200)
	/usr/local/go/src/net/http/server.go:2003 +0x18b fp=0xc02aba1b50 sp=0xc02aba1ae0 pc=0x6d0f4b
net/http.HandlerFunc.ServeHTTP(0xc00085ac00, 0x1fc5900, 0xc008b6e420, 0xc00a21b200)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc02aba1b78 sp=0xc02aba1b50 pc=0x6b0f84
net/http.(*ServeMux).ServeHTTP(0xc000611bf0, 0x1fc5900, 0xc008b6e420, 0xc00a21b200)
	/usr/local/go/src/net/http/server.go:2361 +0x127 fp=0xc02aba1bb8 sp=0xc02aba1b78 pc=0x6b2d37
github.com/opentracing-contrib/go-stdlib/nethttp.Middleware.func2(0x1fd1880, 0xc00fef55e0, 0xc00a21b100)
	/app/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:74 +0x432 fp=0xc02aba1cb0 sp=0xc02aba1bb8 pc=0x176e502
net/http.HandlerFunc.ServeHTTP(0xc00085ac90, 0x1fd1880, 0xc00fef55e0, 0xc00a21b100)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc02aba1cd8 sp=0xc02aba1cb0 pc=0x6b0f84
github.com/prometheus/prometheus/web.withStackTracer.func1(0x1fd1880, 0xc00fef55e0, 0xc00a21b100)
	/app/web/web.go:87 +0x9d fp=0xc02aba1d20 sp=0xc02aba1cd8 pc=0x17c510d
net/http.HandlerFunc.ServeHTTP(0xc00085acc0, 0x1fd1880, 0xc00fef55e0, 0xc00a21b100)
	/usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc02aba1d48 sp=0xc02aba1d20 pc=0x6b0f84
net/http.serverHandler.ServeHTTP(0xc0000872b0, 0x1fd1880, 0xc00fef55e0, 0xc00a21b100)
	/usr/local/go/src/net/http/server.go:2741 +0xab fp=0xc02aba1d78 sp=0xc02aba1d48 pc=0x6b3cdb
net/http.(*conn).serve(0xc02dbca1e0, 0x1fd4a00, 0xc02609c300)
	/usr/local/go/src/net/http/server.go:1847 +0x646 fp=0xc02aba1fc8 sp=0xc02aba1d78 pc=0x6affe6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc02aba1fd0 sp=0xc02aba1fc8 pc=0x45bef1
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
goroutine 1 [chan receive, 257 minutes]:
github.com/oklog/oklog/pkg/group.(*Group).Run(0xc00033bdf8, 0xc0002bebf0, 0x8)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:43 +0xf0
main.main()
	/app/cmd/prometheus/main.go:687 +0x63a6
goroutine 92 [select, 257 minutes]:
main.main.func5(0xffffffffffffffff, 0xc0001900b8)
	/app/cmd/prometheus/main.go:462 +0xe5
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc000072280, 0xc0002beb20)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 19 [syscall, 257 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
goroutine 93 [chan receive, 257 minutes]:
github.com/prometheus/prometheus/discovery.(*Manager).Run(0xc0000a5ae0, 0x0, 0x0)
	/app/discovery/manager.go:171 +0x72
main.main.func7(0x0, 0x0)
	/app/cmd/prometheus/main.go:484 +0x40
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc00000a2a0, 0xc00000a2c0)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 94 [chan receive, 257 minutes]:
github.com/prometheus/prometheus/discovery.(*Manager).Run(0xc0000a5f40, 0x0, 0x0)
	/app/discovery/manager.go:171 +0x72
main.main.func9(0x0, 0x0)
	/app/cmd/prometheus/main.go:498 +0x40
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc00000a300, 0xc00000a320)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 95 [select, 2 minutes]:
github.com/prometheus/prometheus/scrape.(*Manager).Run(0xc000151d60, 0xc000190180, 0x0, 0x0)
	/app/scrape/manager.go:69 +0xdc
main.main.func11(0x0, 0x0)
	/app/cmd/prometheus/main.go:518 +0x7d
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc0001589c0, 0xc00000a340)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 96 [select, 257 minutes]:
main.main.func13(0x0, 0x0)
	/app/cmd/prometheus/main.go:543 +0x16a
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc000452300, 0xc0002bebc0)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 129 [chan receive, 257 minutes]:
main.main.func15(0x0, 0x0)
	/app/cmd/prometheus/main.go:590 +0x351
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc000452360, 0xc0002bebd0)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 130 [chan receive, 257 minutes]:
main.main.func17(0x0, 0x0)
	/app/cmd/prometheus/main.go:606 +0x71
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc00000a360, 0xc00000a380)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 131 [chan receive, 257 minutes]:
main.main.func19(0x0, 0x0)
	/app/cmd/prometheus/main.go:640 +0x41b
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc000072540, 0xc000158a50)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 132 [select, 257 minutes]:
github.com/prometheus/prometheus/web.(*Handler).Run(0xc000323680, 0x1fd4a00, 0xc0000b0a00, 0x0, 0x0)
	/app/web/web.go:490 +0xdcb
main.main.func21(0x0, 0x0)
	/app/cmd/prometheus/main.go:655 +0x40
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc00000a3a0, 0xc0002bebe0)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 133 [select, 127 minutes]:
github.com/prometheus/prometheus/notifier.(*Manager).Run(0xc000132580, 0xc000190240)
	/app/notifier/notifier.go:311 +0xfd
main.main.func23(0x0, 0x0)
	/app/cmd/prometheus/main.go:678 +0x7d
github.com/oklog/oklog/pkg/group.(*Group).Run.func1(0xc0004523c0, 0xc000158ae0, 0xc0002bebf0)
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x27
created by github.com/oklog/oklog/pkg/group.(*Group).Run
	/app/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0xbe
goroutine 117 [select]:
github.com/prometheus/prometheus/discovery.(*Manager).sender(0xc0000a5ae0)
	/app/discovery/manager.go:256 +0x104
created by github.com/prometheus/prometheus/discovery.(*Manager).Run
	/app/discovery/manager.go:170 +0x43
goroutine 119 [select]:
github.com/prometheus/prometheus/discovery.(*Manager).sender(0xc0000a5f40)
	/app/discovery/manager.go:256 +0x104
created by github.com/prometheus/prometheus/discovery.(*Manager).Run
	/app/discovery/manager.go:170 +0x43
goroutine 155 [select, 23 minutes]:
github.com/prometheus/tsdb/wal.(*WAL).run(0xc00011e6c0)
	/app/vendor/github.com/prometheus/tsdb/wal/wal.go:258 +0xdb
created by github.com/prometheus/tsdb/wal.NewSize
	/app/vendor/github.com/prometheus/tsdb/wal/wal.go:245 +0x446
goroutine 120 [select, 2 minutes]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0000b1d00)
	/app/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x10f
created by google.golang.org/grpc.newCCBalancerWrapper
	/app/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x14e
[centos@ip-10-0-26-65 ~]$ 
```

**Comment by amnonh** [comment]
This is a result of running on a machine without enough memory, switch to a bigger machine or define a swap
